
(* This file was auto-generated based on "sintatico.msg". *)

(* Please note that the function [message] can raise [Not_found]. *)

let message =
  fun s ->
    match s with
    | 0 ->
        "POR FAVOR INFORME O PROGRAMA\n"
    | 1 ->
        "POR FAVOR INSIRA UM NOME NO PROGRAMA\n"
    | 2 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 3 ->
        "<YOUR SYNTAX ERROR MESSAGE HERE>\n"
    | 21 ->
        "POR FAVOR INSIRA UM NOME PARA A VARIAVEL\n"
    | 23 ->
        "POR FAVOR INFORME UM TIPO PARA A VARIAVEL\n"
    | 25 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 7 ->
        "DECLARACAO INCORRETA DA FUNCAO\n"
    | 8 ->
        "VIRGULA INCORRETA\n"
    | 28 ->
        "POR FAVOR INSIRA UM TIPO PARA A VARIAVEL\n"
    | 29 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 155 ->
        "DECLARACAO DE VARIAVEL INCORRETA\n"
    | 4 ->
        "POR FAVOR INSIRA A DECLARACAO DA VARIAVEL OU BEGIN\n"
    | 5 ->
        "INSIRA PARENTESES NA DECLARACAO DA FUNCAO\n"
    | 6 ->
        "POR FAVOR INSIRA PARAMETROS PARA A FUNCAO\n"
    | 158 ->
        "POR FAVOR INSIRA UM TIPO PARA A VARIAVEL NA FUNCAO\n"
    | 11 ->
        "POR FAVOR FECHE O PARENTESES NA DECLARACAO DA FUNCAO\n"
    | 12 ->
        "POR FAVOR INSIRA DOIS PONTOS NA DECLARACAO DA FUNCAO\n"
    | 13 ->
        "POR FAVOR INSIRA O TIPO DO RETORNO DA FUNCAO\n"
    | 19 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 20 ->
        "DECLARACAO DE VARIAVEL INCORRETA\n"
    | 32 ->
        "POR FAVOR INSIRA UM COMANDO OU END\n"
    | 152 ->
        "POR FAVOR INSIRA UM END PARA SUA FUNCAO\n"
    | 153 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 166 ->
        "POR FAVOR DECLARE SUA FUNCAO OU VARIAVEL OU INICIE COM BEGIN\n"
    | 33 ->
        "POR FAVOR INSIRA UMA EXPRESSAO PARA O WHILE\n"
    | 78 ->
        "POR FAVOR INSIRA UM OPERADOR OU COMPARADOR PARA SUA EXPRESSAO\n"
    | 44 ->
        "PARAMETROS INSUFICIENTES PARA COMPARACAO DE OU\n"
    | 45 ->
        "POR FAVOR INSIRA UM OPERADOR OU COMPARADOR PARA A EXPRESSAO\n"
    | 46 ->
        "PARAMETROS INVALIDOS PARA SUA MULTIPLICACAO\n"
    | 47 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 53 ->
        "POR FAVOR INSIRA UMA EXPRESSAO PARA O MODULO\n"
    | 54 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 48 ->
        "PARAMETROS INVALIDOS PARA SUA COMPARACAO DE MENOR\n"
    | 55 ->
        "PARAMETROS INVALIDOS PARA SUA COMPARACAO DE MENOR IGUAL\n"
    | 56 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 59 ->
        "PARAMETROS INVALIDOS PARA SUA COMPARACAO DE MENOR\n"
    | 60 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 51 ->
        "PARAMETROS INVALIDOS PARA SUA COMPARACAO DE MAIOR\n"
    | 61 ->
        "PARAMETROS INVALIDOS PARA SUA COMPARACAO DE MAIOR IGUAL\n"
    | 62 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 63 ->
        "PARAMETROS INVALIDOS PARA SUA COMPARACAO DE MAIOR\n"
    | 64 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 65 ->
        "PARAMETROS INVALIDOS PARA SUA COMPARACAO DE IGUALDADE\n"
    | 66 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 67 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO AND\n"
    | 68 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 79 ->
        "POR FAVOR INSIRA UM BEGIN DEPOIS DO WHILE\n"
    | 80 ->
        "POR FAVOR INSIRA UM COMANDO PARA SEU WHILE\n"
    | 149 ->
        "POR FAVOR INSIRA END NO FINAL DO SEU WHILE\n"
    | 150 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 57 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO DE DIVIDIR\n"
    | 58 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 69 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO DE DIFERENTE\n"
    | 70 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 40 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 39 ->
        "ABRE E FECHA PARENTESES COM PARAMENTROS NULOS\n"
    | 43 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 162 ->
        "POR FAVOR INSIRA UM COMANDO PARA SEU PROGRAMA\n"
    | 81 ->
        "POR FAVOR INSIRA O ABRIR PARENTESES NO WRITE\n"
    | 82 ->
        "POR FAVOR INSIRA UM TEXTO OU VARIAVEL PARA SEU WRITE\n"
    | 75 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 76 ->
        "<YOUR SYNTAX ERROR MESSAGE HERE>\n"
    | 84 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 86 ->
        "POR FAVOR INSIRA O FECHAR PARENTESES\n"
    | 87 ->
        "PARAMETROS INVALIDOS PARA SEU WRITE\n"
    | 89 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 91 ->
        "PARAMETROS INVALIDOS PARA SEU READLN\n"
    | 92 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 139 ->
        "POR FAVOR INSIRA UM COMANDO OU END\n"
    | 163 ->
        "POR FAVOR INSIRA UM END NO FINAL DO PROGRAMA\n"
    | 94 ->
        "POR FAVOR INSIRA UMA VARIAVEL PARA SALVAR OS DADOS DO READLN\n"
    | 95 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 97 ->
        "POR FAVOR INSIRA UMA EXPRESSAO VALIDA PARA SEU IF\n"
    | 98 ->
        "POR FAVOR INSIRA UM THEN APOS SEU IF\n"
    | 99 ->
        "POR FAVOR INSIRA UM BEGIN APOS SEU IF\n"
    | 100 ->
        "POR FAVOR INSIRA UM PONTO E VIRGULA\n"
    | 141 ->
        "POR FAVOR INSIRA UM END PARA O SEU IF\n"
    | 142 ->
        "POR FAVOR INSIRA UM ELSE OU END\n"
    | 143 ->
        "POR FAVOR INSIRA UM BEGIN PARA SEU ELSE\n"
    | 144 ->
        "POR FAVOR INSIRA UM COMANDO PARA SEU ELSE\n"
    | 145 ->
        "POR FAVOR INSIRA UM END PARA SEU ELSE\n"
    | 146 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 37 ->
        "POR FAVOR DIGITE UM ABRIR PARENTESES\n"
    | 115 ->
        "PARAMETROS INVALIDOS PARA SUA ATRIBUICAO\n"
    | 41 ->
        "POR FAVOR INSIRA UM IDENTIFICADOR\n"
    | 116 ->
        "POR FAVOR INSIRA UM VALOR PARA SUA VARIAVEL\n"
    | 117 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 38 ->
        "POR FAVOR INSIRA UMA EXPRESSAO OU )\n"
    | 101 ->
        "POR FAVOR INSIRA UMA VARIAVEL PARA SEU FOR\n"
    | 103 ->
        "POR FAVOR INSIRA UMA EXPRESSAO VALIDA PARA SEU FOR\n"
    | 104 ->
        "POR FAVOR INSIRA UMA EXPRESSAO VALIDA PARA SEU FOR\n"
    | 105 ->
        "POR FAVOR INSIRA UM TO PARA SEU FOR\n"
    | 106 ->
        "PARAMETROS INVALIDOS PARA SEU FOR\n"
    | 107 ->
        "POR FAVOR INSIRA UMA DO PARA SEU FOR\n"
    | 108 ->
        "POR FAVOR INSIRA BEGIN NO SEU FOR\n"
    | 109 ->
        "POR FAVOR INSIRA UM COMANDO PARA SEU FOR\n"
    | 136 ->
        "POR FAVOR INSIRA UM END PARA SEU FOR\n"
    | 137 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 164 ->
        "POR FAVOR INSIRA UM PONTO FINAL NO FINAL DO PROGRAMA\n"
    | 110 ->
        "POR FAVOR INSIRA UMA VARIAVEL PARA SEU WHILE\n"
    | 111 ->
        "POR FAVOR INSIRA OF NO SWITCH CASE\n"
    | 112 ->
        "POR FAVOR INSIRA UMA LISTA DE CASOS PARA O SWITCH CASE\n"
    | 131 ->
        "PARAMETROS INVALIDOS PARA SUA EXPRESSAO\n"
    | 132 ->
        "POR FAVOR DIGITE UM COMANDO PARA O CASE\n"
    | 134 ->
        "POR FAVOR INSIRA UM LISTA DE CASES OU ELSE NO SEU SWITCH CASE\n"
    | 129 ->
        "POR FAVOR INSIRA PONTO E VIRGULA\n"
    | 114 ->
        "POR FAVOR INSIRA UMA COMANDO PARA SEU ELSE\n"
    | 128 ->
        "POR FAVOR INSIRA UMA END PARA SEU SWITCH CASE\n"
    | _ ->
        raise Not_found
